version: 2

models:
  
  - name: enriched_flights
    description: 'Joining other tables to get an enriched flight table'
    columns:
      - name: total_delay
        description: 'Total delay, sum of departure_delay and arrival_delay'
        tests:
          - delay_validation:
              severity: warn

  - name: flights_per_carrier
    description: 'Number of flights per carrier'
    columns:
      - name: carrier_id
        description: 'Carrier Identifier'
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_id
      - name: carrier_name
        description: 'Carrier Name'
        tests:
          - relationships:
              to: ref('carriers')
              field: carrier_name
      - name: n_flights
        description: 'Number of flights'
